name: Send Denied Entries Notifications

on:
  schedule:
    # TODO: Change to every Friday.
    # Every day at 10:00pm HST. https://crontab.guru/#0_8_*_*_6
    - cron: "0 8 * * *"

jobs:
  send_denied_entries_notifications:
    runs-on: ubuntu-latest
    steps:
      - run: curl -d "apiKey=${{ vars.API_KEY }}" https://torys.onrender.com/api/public/send-denied-entries-notifications
