name: Update Budgets

on:
  schedule:
    # Every Monday at 10:00am HST. https://crontab.guru/#0_20_*_*_1
    - cron: "0 20 * * 1"

jobs:
  update_budgets:
    runs-on: ubuntu-latest
    steps:
      - run: curl -d "apiKey=${{ vars.API_KEY }}" https://torys.onrender.com/api/public/update-budgets
